name: Deploy to Hostinger (FTP)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # protocol can be 'ftps' (recommended) or 'ftp'. Override with a secret if needed.
          protocol: ${{ secrets.FTP_PROTOCOL || 'ftps' }}
          # Local directory to upload (Astro build output)
          local-dir: dist/
          # Remote directory on Hostinger (e.g., public_html/ or public_html/subsite/)
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          # Start clean remote dir to avoid outdated files (use with caution)
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/README.*
            **/*.zip
            .well-known/**
name: Deploy to Hostinger via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: public_html/
          dangerous-clean-slate: true
